apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone2deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone2app
  template:
    metadata:
      labels:
        app: capstone2app
    spec:
      containers:
      - name: capstone2container
        image: conroy3644/capstone-2:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: capstone2service
spec:
  type: LoadBalancer
  selector:
    app: capstone2app
  ports:
    - port: 5000
      targetPort: 5000